# Site settings
title: The Joined Node Blog
email: roger@datamcfly.com
description: > # this means to ignore newlines until "baseurl:"
  Joined Node is a simple, lightweight, and secure way of running isolated backend code that removed or reduces the need for a backend.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.joinednode.com" # the base hostname & protocol for your site
twitter_username: joinednode
github_username:  joinednode

# Build settings
markdown: kramdown
