# Site settings
title: The Joined Node Blog
email: roger@joinednode.com
description: > # this means to ignore newlines until "baseurl:"
  Joined Node is a simple, lightweight, and secure way of running isolated backend code that removes or reduces the need for a backend.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.joinednode.com" # the base hostname & protocol for your site
twitter_username: joinednode
github_username:  joinednode

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
paginate:         5

github:
  repo: /joinednode/joinednode-blog
  branch: gh-pages

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
